### ISSUE TITLE
Name change for page Vokabulare

### ISSUE THREAD

**Issue by mrchristian** [TIBHannover/semantic-glossar#42]
On the following page:

https://climatekg.semanticclimate.net/index.php?title=Vokabulare

Would it be possible to change page name or at least display page name to 'Begriffe suchen & bearbeiten'?

And to change the first field label to Glossar: from Vokabular:

**Comment by whitecryst** [comment]
yes its possible.

to change the page Title:
a) you can move the page Vokabulare to a new Page but i thing the "&" would be not allowed as a pagename
b) we can install the extension Dispplaytitle, that allows to display a Page title other than the real page name
https://www.mediawiki.org/wiki/Extension:Display_Title

**Comment by whitecryst** [comment]
First field label was already changed to "Vokabular" via  editing the Form page https://climatekg.semanticclimate.net/index.php?title=Formular:Vokabular (also linked in the menu Entwicklung->Wiki->Begriffsuche Formular)

**Comment by calnfynn** [comment]
_Glossare > Begriff suchen & bearbeiten_ in the menu now links to: https://climatekg.semanticclimate.net/index.php?title=Begriff_suchen_%26_bearbeiten
