### ISSUE TITLE
Add Tag field label on Co-Site Glossar

### ISSUE THREAD

**Issue by mrchristian** [TIBHannover/semantic-glossar#63]
https://tibhannover.github.io/co-site-glossar/cosite001.html

**Comment by calnfynn** [comment]
I took the tag label out because TH Köln's request was that it shouldn't be in the PDF, which I prioritised. I'll see if I can maybe add it for the website only with CSS

**Comment by calnfynn** [comment]
fixed. labels are on the website again as they should be and the pdf is still as requested
